UKW_sklep_czw/Models/Film.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UKW_sklep_czw.Models
{
	public class Film
	{
		public int FilmId { get; set; }

		[Required(ErrorMessage = "Podaj tytuł")]
		public string Title { get; set; }

		public string Director { get; set; }

		[StringLength(600, ErrorMessage = "Przekroczono limit znaków")]
		public string Description { get; set; }

		public decimal? Price { get; set; }

		public string Poster { get; set; }

		public int CategoryId { get; set; }
		//public int CategoryCategoryId { get; set; }

		//[ForeignKey("Category")]
		//public int KategoriaId { get; set; }

		public Category Category { get; set; }
	}
}

UKW_sklep_czw/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using UKW_sklep_czw.DAL;
using UKW_sklep_czw.Infrastructure;
using UKW_sklep_czw.Models;

namespace UKW_sklep_czw.Controllers
{
    public class CartController : Controller
    {
        FilmsContext db;

        public CartController(FilmsContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            var cart = CartManager.GetItems(HttpContext.Session);
            ViewBag.Total = CartManager.GetCartValue(HttpContext.Session);

            return View(cart);
        }

        public IActionResult AddToCart(int filmId, string returnUrl = null)
        {
            CartManager.AddToCart(HttpContext.Session, filmId, db);

            //if (!string.IsNullOrEmpty(returnUrl))
            //{
            //    return Redirect(returnUrl);
            //}

            // PROBLEM Z ROUTINGIEM!!!!
            // Zbyt ogólny dla kategorii i wyłapuje /Cart (czyli Index) jako nazwę kategorii
            // Zmienić lub przenieść na koniec pod defaulta
            return RedirectToAction("Index");
        }


        public IActionResult RemoveFromCart(int id)
        {
            var model = new RemoveViewModel()
            {
                itemId = id,
                itemQuantity = CartManager.RemoveFromCart(HttpContext.Session, id),
                cartValue = CartManager.GetCartValue(HttpContext.Session)
            };

            return Json(model);
        }
    }
}

UKW_sklep_czw/Controllers/FilmsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UKW_sklep_czw.DAL;
using UKW_sklep_czw.Migrations;
using UKW_sklep_czw.Models;

namespace UKW_sklep_czw.Controllers
{
    public class FilmsController : Controller
    {
        FilmsContext db;
        IWebHostEnvironment webHost;

        public FilmsController(FilmsContext db, IWebHostEnvironment webHost)
        {
            this.db = db;
            this.webHost = webHost;
        }

        [HttpGet]
        public IActionResult AddFilm()
        {
            AddViewModel model = new AddViewModel();

            model.AllCategories = db.Categories.ToList();

            return View(model);
        }

        [HttpPost]
        public IActionResult AddFilm(AddViewModel model)
        {
            var posterFolderPath = Path.Combine(webHost.WebRootPath, "posters");

            var uniquePosterName = model.Poster.FileName + "_" + Guid.NewGuid() + Path.GetExtension(model.Poster.FileName);


            var filePath = Path.Combine(posterFolderPath, uniquePosterName);

            model.Poster.CopyTo(new FileStream(filePath, FileMode.Create));

            model.NewFilm.Poster = uniquePosterName;
            db.Films.Add(model.NewFilm);

            db.SaveChanges();

            return RedirectToAction("AddFilm");
        }



		public IActionResult FilmsList(string categoryName)
        {
            var category = db.Categories.Include("Films").Where(c => c.Name.ToUpper() == categoryName.ToUpper()).Single();
			var films = category.Films.ToList();

			return View(films);
        }

        public IActionResult Details(int filmId)
        {
            var film = db.Films.Find(filmId);

            if (film != null)
            {
                db.Categories.Find(film.CategoryId);
            }

            return View(film);
        }

        public IActionResult AllFilms()
        {
            return View(db.Films.ToList());
        }
    }
}

UKW_sklep_czw/ViewComponents/SideMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UKW_sklep_czw.DAL;

namespace UKW_sklep_czw.ViewComponents
{
    public class SideMenuViewComponent : ViewComponent
    {
        FilmsContext db;

        public SideMenuViewComponent(FilmsContext db)
        {
            this.db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync(string categoryName)
        {
            var category = db.Categories.Include("Films").Where(c => c.Name.ToUpper() == categoryName.ToUpper()).FirstOrDefault();

            var films = category.Films.OrderBy(f => f.Title).ToList();

            return await Task.FromResult(View("_SideMenu", films));
        }
    }
}

UKW_sklep_czw/Views/Films/AddFilm.cshtml
@model AddViewModel

@{
    ViewData["Title"] = "Dodawanie filmu";
}

@using(Html.BeginForm("AddFilm", "Films", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	<div>
		<div class="form-group">
			<b>@Html.LabelFor(m => m.NewFilm.Title, "Tytuł:") </b>
			@Html.TextBoxFor(m => m.NewFilm.Title, new { @class="form-control", @required = true})
		</div>
		<div class="form-group">
			<b>@Html.LabelFor(m => m.NewFilm.Director, "Reżyser:") </b>
			@Html.TextBoxFor(m => m.NewFilm.Director, new { @class = "form-control", @required = true })
		</div>
		<div class="form-group">
			<b>@Html.LabelFor(m => m.NewFilm.Price, "Cena:") </b>
			@Html.TextBoxFor(m => m.NewFilm.Price, new { Type = "number", @class = "form-control", @required = true })
		</div>
		<div class="form-group">
			<b>@Html.LabelFor(m => m.NewFilm.Description, "Opis:") </b>
			@Html.TextAreaFor(m => m.NewFilm.Description, new { @class = "form-control", @required = true })
		</div>
		<div class="form-group">
			<b>@Html.LabelFor(m => m.Poster, "Plakat:") </b>
			@Html.TextBoxFor(m => m.Poster, new { Type = "file", @class = "form-control-file", @required = true })
		</div>
		<div class="form-check">
		@foreach (var category in Model.AllCategories)
		{
			@Html.RadioButtonFor(m => m.NewFilm.CategoryId, category.CategoryId, new { @class="from-check-input"})
			@category.Name
			<br />
		}
		</div>
	</div>
	<div class="form-group">
	<button type="submit" class="btn btn-primary">Dodaj</button>

	</div>
}

UKW_sklep_czw/Views/Films/AllFilms.cshtml
@model IEnumerable<Film>

<div class="container all-films">
	<div class="row g-4">
		@foreach (var film in Model)
		{
		<div class="col-md-4 col-sm-6 d-flex justify-content-center">
				<a href="@Url.Action("Details","Films",new {filmId=film.FilmId})"><img src="~/posters/@film.Poster" alt="Film @film.Poster" class="poster"></a>
		</div>
		}
	</div>
</div>

UKW_sklep_czw/Views/Films/Details.cshtml
@model Film


<table id="details">
	<tr>
		<td>
			<h2>@Model.Category.Name</h2>

			@(await Component.InvokeAsync("SideMenu", new { categoryName = Model.Category.Name }))
		</td>
		<td>
			<img src="~/posters/@Model.Poster" height="250px" alt="Grafika @Model.Poster"/>
		</td>
		<td>
			<ul>
				<li><b>Tytuł: </b>@Model.Title</li>
				<li><b>Reżyser: </b>@Model.Director</li>
				<li><b>Cena: </b>@Model.Price zł</li>
				<li><b>Opis: </b>@Model.Description</li>
			</ul>
			<p><a href="@Url.Action("AddToCart", "Cart", new {filmId = Model.FilmId, returnUrl = Url.Action("Details", "Films", new { filmId = Model.FilmId })})">🛒</a></p>
		</td>
	</tr>
</table>

UKW_sklep_czw/Views/Films/FilmsList.cshtml
@model IEnumerable<Film>
@{
	ViewData["Title"] = "Kategoria " + Model.FirstOrDefault().Category.Name;
}

<table class="table table-striped">
	<thead>
		<tr>
			<th>Tytuł filmu</th>
			<th>Reżyser</th>
			<th>Opis</th>
			<th>Cena</th>
		</tr>
	</thead>
	<tbody>
		@foreach(var film in Model)
		{
			<tr>
				<td>@film.Title</td>
				<td>@film.Director</td>
				<td>@film.Description</td>
				<td>@film.Price zł</td>
				<td><a href="@Url.Action("Details", "Films", new { filmId = film.FilmId })"> 🔎 </a></td>
			</tr>
		}
	</tbody>
</table>